development:
  adapter: async

test:
  adapter: async

production:
  adapter: postgresql
  url: postgres://iqyyqdclklsbop:f57a5062053e65fadc7ecf476c101696ba00714fe03dfe00027b2734c3844359@ec2-23-23-234-118.compute-1.amazonaws.com:5432/d5gissfffjbmrl
  channel_prefix: nameofapp_production
